-- Neo-tree is a Neovim plugin to browse the file system
-- https://github.com/nvim-neo-tree/neo-tree.nvim

--  return {
--  { 'nvim-neo-tree/neo-tree.nvim',
--     enabled = true,
--   version = '*',
--   dependencies = {
--     'nvim-lua/plenary.nvim',
--     'nvim-tree/nvim-web-devicons', -- not strictly required, but recommended
--     'MunifTanjim/nui.nvim',
--   },
--   cmd = 'Neotree',
--   keys = {
--     { '<leader> E', ':Neotree reveal<CR>', desc = 'NeoTree reveal', silent = true },
--   },
--   opts = {
--     filesystem = {
--       window = {
--         mappings = {
--           ['\\'] = 'close_window',
--         },
--       },
--     },
--   },
-- },
--   { -- filetree
--     'nvim-tree/nvim-tree.lua',
--     enabled = false,
--     keys = {
--       { '<leader> E', ':NvimTreeToggle<cr>', desc = 'toggle nvim-tree' },
--     },
--     config = function()
--       require('nvim-tree').setup {
--         disable_netrw = true,
--         update_focused_file = {
--           enable = true,
--         },
--         git = {
--           enable = true,
--           ignore = false,
--           timeout = 500,
--         },
--         diagnostics = {
--           enable = true,
--         },
--       }
--     end,
--   },

--   -- or a different filetree
  
-- }
